import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Mind Bridge App",
    description: "Generated by Juan Manuel Panozzo Zénere",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const supabase = createServerComponentClient({ cookies });
    const {
        data: { session },
    } = await supabase.auth.getSession();

    if (!session) {
        return redirect("/login");
    }

    return (
        <html lang="en">
            <body className={inter.className}>
                <Theme className="bg-gradient-to-tr from-indigo-600/10 to-cyan-600/10 min-h-screen">
                    <Navbar />
                    <section className="container grid grid-cols-1 md:grid-cols-3 gap-2 mx-auto mt-4">
                        {children}
                    </section>
                </Theme>
            </body>
        </html>
    );
}